#!/bin/sh
#
# Start/stop fcgiwrap
#

PIDFILE=/var/run/fcgiwrap.pid

case "$1" in
  start)
	printf "Starting fcgiwrap..."
	start-stop-daemon -S -q -b -p $PIDFILE -x /usr/bin/spawn-fcgi \
		-- -p 9001 -P $PIDFILE /usr/sbin/fcgiwrap
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping fcgiwrap..."
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
