#!/bin/sh
#
# Start crond....
#

PIDFILE=/var/run/hostapd.pid

start() {
    printf "Starting hostapd: "
    start-stop-daemon -S -q -m -b -p $PIDFILE \
		-x /usr/sbin/hostapd -- -B /etc/hostapd.conf
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping hostapd: "
    start-stop-daemon -K -q -p $PIDFILE \
		-x /usr/sbin/hostapd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
