#!/bin/sh
#
# Start/stop wsapi
#

PIDFILE=/var/run/wsapi.pid

case "$1" in
  start)
	printf "Starting wsapi..."
	start-stop-daemon -S -q -b -p $PIDFILE -x /usr/bin/spawn-fcgi \
		-- -p 9000 -P $PIDFILE /usr/bin/wsapi.fcgi
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping wsapi..."
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
