#!/bin/sh
#
# Start live-streamer
#

SENSOR_TYPE=$(. /lib/scripts/hardware.sh; detect_sensor_type)

start() {
    echo -n "Starting live-streamer: "
    start-stop-daemon -S -q -m -b -p /var/run/live-streamer.pid \
                      -x live-streamer -- -S ${SENSOR_TYPE}
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo -n "Stopping live-streamer: "
    start-stop-daemon -K -q -p /var/run/live-streamer.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    usleep 1000000
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
