#!/bin/sh
#
# Start crond....
#

PIDFILE=/var/run/crond.pid

start() {
    printf "Starting crond: "
    mkdir -p /var/spool/cron
    ln -s /etc/crontabs /var/spool/cron/ 2>/dev/null

    start-stop-daemon -S -q -m -b -p $PIDFILE \
		-x /usr/sbin/crond -- -f -S -c /etc/crontabs -l 5
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping crond: "
    start-stop-daemon -K -q -p $PIDFILE \
		-x /usr/sbin/crond
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
