#!/bin/sh
#
# Start sysled....
#

PIDFILE=/var/run/sysled.pid

start() {
    printf "Starting sysled: "
    start-stop-daemon -S -q -m -b -p $PIDFILE \
		-x /usr/sbin/sysled.sh -- 3
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping sysled: "
    start-stop-daemon -K -q -p $PIDFILE \
		-x /usr/sbin/sysled.sh
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
